In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings("ignore")

In [5]:
df=sns.load_dataset('tips')

In [6]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [7]:
#predict what is the time? if any one is visiting -- is it lunch or dinner?
# time is the target variable

df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['time']=encoder.fit_transform(df['time'])

In [9]:
X=df.drop('time',axis=1)
y=df['time']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.impute import SimpleImputer # for missing value
from sklearn.preprocessing import OneHotEncoder # for encoding
from sklearn.preprocessing import StandardScaler # for Scaling

from sklearn.pipeline import Pipeline # a sequesnce of data transformer
from sklearn.compose import ColumnTransformer # Groups all the pipeline steps for each of the columns

In [12]:
cat_cols=["sex","smoker","day"]
num_cols=["total_bill","tip","size"]

In [ ]:
# Feature Engineering automatio using pipeline and columnTransformer

Numerical_pipeline=Pipeline(steps=[("imputation",SimpleImputer(strategy='median')),
                ("scaling",StandardScaler())])

categorical_pipeline=Pipeline(steps=[("imputation",SimpleImputer(strategy='most_frequent')),
                ("encoding",OneHotEncoder())])
                

In [14]:
preprocessor=ColumnTransformer([("num_pipeline",Numerical_pipeline,num_cols),
                   ("cat_pipeline",categorical_pipeline,cat_cols)])

preprocessor

,transformers,"[('num_pipeline', ...), ('cat_pipeline', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True
,force_int_remainder_cols,'deprecated'
,missing_values,nan
,strategy,'median'
,fill_value,None


In [15]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [16]:
X_train,X_test

(array([[-0.79306155, -0.2580329 , -0.61214068, ...,  1.        ,
          0.        ,  0.        ],
        [ 0.46322744, -0.74211442, -0.61214068, ...,  1.        ,
          0.        ,  0.        ],
        [ 0.80730659,  0.6399734 , -0.61214068, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-1.65383098, -1.46472887, -0.61214068, ...,  0.        ,
          0.        ,  0.        ],
        [ 1.64749986,  0.32426806, -0.61214068, ...,  0.        ,
          1.        ,  0.        ],
        [ 2.75289699, -0.41237773,  0.45363997, ...,  1.        ,
          0.        ,  0.        ]], shape=(195, 11)),
 array([[-0.04546101,  0.06468811, -0.61214068,  0.        ,  1.        ,
          1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        ],
        [-1.30860871, -0.76316144, -0.61214068,  0.        ,  1.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ],
        [ 0.49

In [1]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

In [2]:
rf

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [21]:
from sklearn.model_selection import RandomizedSearchCV

params={'max_depth':[1,2,3,4,5,10,None],
'n_estimators':[30,40,50,100,200,300],
'criterion':['gini','entropy']
}

In [22]:
clf=RandomizedSearchCV(rf,param_distributions=params,cv=5,verbose=3,scoring='accuracy',n_iter=10)

In [23]:
clf

,estimator,RandomForestClassifier()
,param_distributions,"{'criterion': ['gini', 'entropy'], 'max_depth': [1, 2, ...], 'n_estimators': [30, 40, ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,3
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [24]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=entropy, max_depth=10, n_estimators=40;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, n_estimators=40;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, n_estimators=40;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, n_estimators=40;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, n_estimators=40;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=1, n_estimators=50;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=1, n_estimators=50;, score=0.897 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=1, n_estimators=50;, score=0.846 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=1, n_estimators=50;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=1, n_estimators=50;, score=0.795 total time=  

,estimator,RandomForestClassifier()
,param_distributions,"{'criterion': ['gini', 'entropy'], 'max_depth': [1, 2, ...], 'n_estimators': [30, 40, ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,3
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [25]:
clf.best_params_

{'n_estimators': 40, 'max_depth': 2, 'criterion': 'entropy'}

In [26]:
clf.best_score_

np.float64(0.9589743589743589)

In [27]:
final_model=clf.best_estimator_

In [28]:
final_model.predict(X_test)

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1])

In [29]:
# Now data is ready now built the multiple model


from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


In [30]:
models={"support vector machine":SVC(),
        "DT classifier": DecisionTreeClassifier(),
        "Logistic Regression":LogisticRegression(),
        "RF":RandomForestClassifier()
          }

In [31]:
from sklearn.metrics import accuracy_score

def model_train_eval(X_train,X_test,y_train,y_test,models):
    evaluation={}
    for i in range(len(models)):
        model=list(models.values())[i]
        model.fit(X_train,y_train)
        y_pred=model.predict(X_test)
        model_score=accuracy_score(y_test,y_pred)
        evaluation[list(models.values())[i]]=model_score
    return evaluation

In [32]:
model_train_eval(X_train,X_test,y_train,y_test,models)

{SVC(): 0.9591836734693877,
 DecisionTreeClassifier(): 0.9387755102040817,
 LogisticRegression(): 1.0,
 RandomForestClassifier(): 0.9591836734693877}